# Generated by Django 4.2 on 2023-04-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                ("curse_code", models.CharField(max_length=10)),
                (
                    "level",
                    models.CharField(
                        choices=[("B", "Basic"), ("I", "Intermed"), ("A", "Advanced")],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("rg", models.CharField(max_length=9)),
                ("cpf", models.CharField(max_length=12)),
                ("born_date", models.DateField()),
            ],
        ),
    ]
