# Generated by Django 4.2 on 2023-04-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("M", "Morning"), ("A", "Afternoon"), ("N", "Night")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "curse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.curse"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.student"
                    ),
                ),
            ],
        ),
    ]
